[package]
name = "ray_tracer_challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-noise = "0.8.7"
dyn-clone = "1.0.11"
nalgebra = "0.32.2"

